# keywords.py
# COMPLETE SDG KEYWORDS DATABASE
# UPDATED: 3600+ TERMS WITH EXPANDED COVERAGE
# NEW: Scientific communication, data visualization, software tools, editorial processes, AI detection, publication ethics

# ============================================================================
# SDG 1: No Poverty (55+ terms)
# ============================================================================

SDG1_KEYWORDS = {
    "exact_phrases": {
        "extreme poverty": 3,
        "social protection": 3,
        "vulnerable population": 3,
        "poverty alleviation": 3,
        "poverty reduction": 3,
        "multidimensional poverty": 3,
        "poor household": 3,
        "social safety net": 2,
        "conditional cash transfer": 2,
        "poverty line": 2,
        "intergenerational poverty": 3,
        "absolute poverty": 3,
        "relative poverty": 3,
        "working poor": 2,
        "asset poverty": 2,
        "wealth disparity": 2,
        "economic marginalization": 2,
        "economic vulnerability": 2,
        "social assistance": 2,
        "poor communities": 3,
        "poverty trap": 3,
        "basic income": 2,
        "safety net": 2,
        "food insecurity": 2,
        "low socioeconomic": 2,
        "economic shock": 2,
        "multidimensional poverty index": 3,
        "poverty dynamics": 2,
        "chronic poverty": 3,
        "transient poverty": 2,
        "poverty gap": 2,
        "poverty severity": 2,
        "social exclusion poverty": 3,
        "capability deprivation": 2,
        "livelihood vulnerability": 2,
        "asset deprivation": 2,
        "housing poverty": 2,
        "energy poverty": 2,
        "transport poverty": 2,
        "digital poverty": 2,
        "time poverty": 2,
        "multidimensional deprivation": 3,
    },
    "single_words": {
        "poverty": 3,
        "livelihood": 2,
        "homeless": 3,
        "slum": 2,
        "microfinance": 2,
        "low-income": 2,
        "indigent": 3,
        "deprivation": 3,
        "welfare": 2,
        "homelessness": 3,
        "underprivileged": 3,
        "destitution": 3,
        "subsistence": 2,
        "charity": 2,
        "food bank": 2,
        "income inequality": 2,
        "indigence": 3,
        "penury": 3,
        "beggary": 2,
    },
    "stems": {
        "pover": 2,
        "destitut": 2,
        "depriv": 2,
        "vulner": 2,
        "inequ": 2,
    }
}

# ============================================================================
# SDG 2: Zero Hunger (60+ terms)
# ============================================================================

SDG2_KEYWORDS = {
    "exact_phrases": {
        "food security": 3,
        "sustainable agriculture": 3,
        "crop yield": 2,
        "agricultural productivity": 2,
        "smallholder farmer": 3,
        "soil fertility": 2,
        "food supply chain": 2,
        "zero hunger": 3,
        "food access": 2,
        "subsistence farming": 2,
        "crop failure": 3,
        "hidden hunger": 3,
        "post-harvest loss": 3,
        "food system": 3,
        "food desert": 3,
        "land grabbing": 2,
        "micronutrient deficiency": 3,
        "food sovereignty": 2,
        "crop diversification": 2,
        "soil degradation": 2,
        "food waste reduction": 2,
        "sustainable intensification": 2,
        "vertical farming": 2,
        "precision agriculture": 2,
        "food fortification": 2,
        "nutrition security": 3,
        "dietary diversity": 2,
        "food assistance": 2,
        "school feeding": 2,
        "acute malnutrition": 3,
        "chronic malnutrition": 3,
        "food utilization": 2,
        "food stability": 2,
        "food availability": 2,
        "dietary quality": 2,
        "complementary feeding": 2,
        "therapeutic feeding": 2,
        "emergency food aid": 2,
        "food stock": 2,
        "grain reserve": 2,
    },
    "single_words": {
        "hunger": 3,
        "malnutrition": 3,
        "undernutrition": 3,
        "famine": 3,
        "stunting": 3,
        "wasting": 3,
        "irrigation": 2,
        "nutrition": 3,
        "agroecology": 2,
        "breastfeeding": 2,
        "agroforestry": 2,
        "hydroponics": 2,
        "aquaponics": 2,
        "undernourishment": 3,
        "thiamin": 2,
        "riboflavin": 2,
        "niacin": 2,
    },
    "stems": {
        "hungr": 2,
        "malnour": 2,
        "undernour": 2,
        "agricultur": 2,
        "farming": 2,
        "crop": 2,
        "food": 2,
    }
}

# ============================================================================
# SDG 3: Good Health & Well-being (110+ terms)
# ============================================================================

SDG3_KEYWORDS = {
    "exact_phrases": {
        "maternal health": 3,
        "child mortality": 3,
        "non-communicable disease": 3,
        "mental health": 3,
        "universal health coverage": 3,
        "clinical trial": 2,
        "drug resistance": 2,
        "antimicrobial resistance": 3,
        "drug delivery": 2,
        "medicinal chemistry": 2,
        "life expectancy": 3,
        "health outcome": 2,
        "health equity": 2,
        "primary care": 2,
        "health system": 2,
        "infant mortality": 3,
        "neonatal mortality": 3,
        "under-five mortality": 3,
        "reproductive health": 3,
        "family planning": 2,
        "sexual health": 2,
        "substance abuse": 2,
        "opioid crisis": 2,
        "suicide prevention": 2,
        "neglected tropical disease": 3,
        "zoonotic disease": 2,
        "vector-borne disease": 2,
        "air pollution health": 2,
        "waterborne disease": 2,
        "occupational health": 2,
        "health promotion": 2,
        "disease prevention": 2,
        "health literacy": 2,
        "digital health": 2,
        "personalized medicine": 2,
        "precision medicine": 2,
        "gene therapy": 2,
        "point-of-care": 2,
        "enzyme inhibition": 3,
        "cell viability": 3,
        "mtt assay": 3,
        "srb assay": 3,
        "apoptosis": 3,
        "necrosis": 3,
        "cell cycle arrest": 3,
        "antiviral activity": 3,
        "antibacterial activity": 3,
        "antifungal activity": 3,
        "cytotoxic activity": 3,
        "therapeutic index": 3,
        "selectivity index": 3,
        "blood-brain barrier": 3,
        "bioavailability": 3,
        "pharmacokinetic parameter": 3,
        "pharmacodynamic parameter": 3,
        "admet profile": 3,
        "drug likeness": 2,
        "lead compound": 2,
    },
    "single_words": {
        "disease": 3,
        "mortality": 3,
        "vaccine": 3,
        "pandemic": 3,
        "healthcare": 3,
        "hospital": 2,
        "epidemic": 3,
        "tuberculosis": 3,
        "malaria": 3,
        "HIV": 3,
        "cancer": 3,
        "diabetes": 3,
        "cardiovascular": 3,
        "toxicology": 2,
        "pharmacology": 2,
        "biocompatibility": 2,
        "sanitation": 2,
        "morbidity": 3,
        "contraception": 2,
        "addiction": 2,
        "immunotherapy": 2,
        "biomarker": 2,
        "diagnostic": 2,
        "telemedicine": 2,
        "cytotoxicity": 3,
        "anticancer": 3,
        "antimicrobial": 3,
        "antibacterial": 3,
        "antifungal": 3,
        "antiviral": 3,
        "anti-inflammatory": 3,
        "analgesic": 3,
        "antioxidant": 3,
        "ic50": 3,
        "ec50": 3,
        "pharmacokinetics": 3,
        "pharmacodynamics": 3,
        "bioavailability": 3,
        "neurodegenerative": 3,
        "autoimmune": 3,
        "metabolic syndrome": 2,
        "obesity": 2,
        "hypertension": 2,
    },
    "stems": {
        "diseas": 2,
        "mortal": 2,
        "vaccin": 2,
        "pandem": 2,
        "epidem": 2,
        "health": 2,
        "carcin": 2,
        "diabet": 2,
        "cardio": 2,
        "toxicol": 2,
        "pharmacol": 2,
        "therap": 2,
        "medic": 2,
        "cytotox": 2,
        "anticanc": 2,
        "antimicrob": 2,
        "apoptos": 2,
    }
}

# ============================================================================
# SDG 4: Quality Education (UPDATED: 90+ terms including scientific communication)
# ============================================================================

SDG4_KEYWORDS = {
    "exact_phrases": {
        "school enrollment": 3,
        "teacher training": 3,
        "inclusive education": 3,
        "early childhood education": 3,
        "vocational training": 3,
        "lifelong learning": 3,
        "educational inequality": 3,
        "digital literacy": 2,
        "learning outcome": 3,
        "quality education": 3,
        "adult education": 3,
        "access to school": 3,
        "educational attainment": 2,
        "chemistry education": 2,
        "science education": 2,
        "foundational literacy": 3,
        "primary education": 3,
        "secondary education": 2,
        "higher education": 2,
        "technical education": 2,
        "STEM education": 3,
        "online learning": 2,
        "remote learning": 2,
        "educational technology": 2,
        "curriculum development": 2,
        "teacher shortage": 2,
        "school infrastructure": 2,
        "girls education": 3,
        "special education": 2,
        "early learning": 2,
        "educational equity": 3,
        "learning poverty": 3,
        "education financing": 2,
        "teacher professional development": 2,
        "educational assessment": 2,
        "scientific communication": 3,
        "research communication": 3,
        "data literacy": 3,
        "visualization literacy": 3,
        "academic writing": 2,
        "research impact": 2,
        "clarity of research": 2,
        "effective figures": 2,
        "science writing": 2,
        "technical writing": 2,
        "grant writing": 2,
        "academic communication": 3,
        "scholarly communication": 3,
        "research training": 2,
        "methodology training": 2,
        "data science education": 2,
        "computational thinking": 2,
        "information literacy": 3,
        "media literacy": 2,
        "critical thinking education": 2,
        "problem solving education": 2,
        "collaborative learning": 2,
        "project based learning": 2,
        "inquiry based learning": 2,
        "blended learning": 2,
        "flipped classroom": 2,
    },
    "single_words": {
        "literacy": 3,
        "dropout": 3,
        "pedagogy": 2,
        "numeracy": 3,
        "preschool": 2,
        "kindergarten": 2,
        "scholarship": 2,
        "didactic": 2,
        "andragogy": 2,
        "heutagogy": 2,
    },
    "stems": {
        "liter": 2,
        "enrollment": 2,
        "educat": 2,
        "learn": 2,
        "teach": 2,
        "train": 2,
        "school": 2,
        "communic": 2,
        "literaci": 2,
    }
}

# ============================================================================
# SDG 5: Gender Equality (55+ terms)
# ============================================================================

SDG5_KEYWORDS = {
    "exact_phrases": {
        "gender equality": 3,
        "women's empowerment": 3,
        "gender discrimination": 3,
        "gender gap": 3,
        "female genital mutilation": 3,
        "child marriage": 3,
        "intimate partner violence": 3,
        "gender-based violence": 3,
        "glass ceiling": 3,
        "women's rights": 3,
        "gender parity": 3,
        "gender wage gap": 3,
        "female leadership": 2,
        "women in stem": 2,
        "women in chemistry": 2,
        "reproductive rights": 2,
        "gender mainstreaming": 2,
        "gender norm": 2,
        "gender stereotype": 2,
        "women's health": 2,
        "women's education": 2,
        "women's economic empowerment": 3,
        "gender justice": 3,
        "sexual harassment": 3,
        "domestic violence": 3,
        "honor killing": 3,
        "trafficking women": 3,
        "gender audit": 2,
        "gender budgeting": 2,
        "gender quota": 2,
        "transgender rights": 2,
        "gender identity": 2,
        "sexual orientation": 2,
        "women in leadership": 2,
        "female entrepreneurship": 2,
        "maternal mortality": 2,
        "adolescent girl": 2,
    },
    "single_words": {
        "sexism": 3,
        "misogyny": 3,
        "patriarchy": 2,
        "masculinity": 2,
        "LGBTQ": 2,
        "feminism": 2,
        "empowerment": 2,
        "androcracy": 2,
        "matriarchy": 2,
    },
    "stems": {
        "gender": 2,
        "women": 2,
        "female": 2,
        "femin": 2,
        "discrimin": 2,
        "empower": 2,
        "equal": 2,
    }
}

# ============================================================================
# SDG 6: Clean Water & Sanitation (70+ terms)
# ============================================================================

SDG6_KEYWORDS = {
    "exact_phrases": {
        "drinking water": 3,
        "water scarcity": 3,
        "open defecation": 3,
        "water quality": 3,
        "water treatment": 3,
        "water pollution": 3,
        "heavy metal removal": 3,
        "ion exchange": 2,
        "membrane filtration": 3,
        "photocatalysis water": 3,
        "contaminant removal": 3,
        "arsenic removal": 3,
        "lead removal": 3,
        "dye degradation": 3,
        "water purification": 3,
        "metal organic framework water": 3,
        "advanced oxidation": 3,
        "reverse osmosis": 3,
        "water reuse": 2,
        "water stress": 3,
        "waterborne disease": 3,
        "water access": 3,
        "water security": 3,
        "water conservation": 2,
        "water governance": 2,
        "integrated water management": 2,
        "rainwater harvesting": 2,
        "greywater recycling": 2,
        "blackwater treatment": 2,
        "septic system": 2,
        "hygiene promotion": 2,
        "activated carbon": 2,
        "biochar water": 2,
        "hydrogel water": 2,
        "capacitive deionization": 2,
        "forward osmosis": 2,
        "membrane distillation": 2,
        "groundwater recharge": 2,
        "aquifer storage": 2,
        "desalination plant": 3,
        "wastewater treatment plant": 3,
        "water distribution network": 2,
        "water loss reduction": 2,
    },
    "single_words": {
        "sanitation": 3,
        "wastewater": 3,
        "desalination": 3,
        "adsorption": 3,
        "nanofiltration": 3,
        "sorbent": 3,
        "groundwater": 2,
        "watershed": 2,
        "WASH": 3,
        "electrocoagulation": 2,
        "disinfection": 2,
        "chlorination": 2,
        "ultrafiltration": 2,
        "microfiltration": 2,
        "flocculation": 2,
        "coagulation": 2,
        "sedimentation": 2,
        "filtration": 2,
        "latrine": 2,
        "handwashing": 2,
        "toilet": 2,
        "sewerage": 2,
        "effluent": 2,
    },
    "stems": {
        "water": 2,
        "sanit": 2,
        "purif": 2,
        "filtr": 2,
        "adsorb": 2,
        "desalin": 2,
        "contamin": 2,
        "removal": 2,
        "degrad": 2,
        "oxid": 2,
        "membran": 2,
        "wastewat": 2,
    }
}

# ============================================================================
# SDG 7: Affordable & Clean Energy (155+ terms)
# ============================================================================

SDG7_KEYWORDS = {
    "exact_phrases": {
        "renewable energy": 3,
        "solar power": 3,
        "wind energy": 3,
        "energy efficiency": 3,
        "energy access": 3,
        "clean cooking": 3,
        "energy transition": 3,
        "hydrogen evolution": 3,
        "oxygen evolution": 3,
        "fuel cell": 3,
        "water splitting": 3,
        "hydrogen production": 3,
        "solar fuel": 3,
        "CO2 reduction": 3,
        "artificial photosynthesis": 3,
        "perovskite solar": 3,
        "energy storage": 3,
        "lithium ion": 3,
        "solid state battery": 3,
        "green energy": 3,
        "clean energy": 3,
        "energy poverty": 3,
        "solar cell": 3,
        "organic photovoltaic": 3,
        "dye-sensitized solar": 3,
        "quantum dot solar": 3,
        "wind turbine": 2,
        "green hydrogen": 3,
        "ammonia fuel": 2,
        "metal-air battery": 2,
        "redox flow battery": 2,
        "lithium sulfur": 2,
        "solid electrolyte": 2,
        "energy harvesting": 2,
        "smart grid": 2,
        "rural electrification": 3,
        "energy justice": 2,
        "sodium ion": 2,
        "proton conductivity": 3,
        "proton transport": 3,
        "proton conduction": 3,
        "protonic ceramic fuel cell": 3,
        "solid oxide fuel cell": 3,
        "solid oxide electrolysis": 3,
        "intermediate temperature electrochemical": 3,
        "proton exchange membrane": 3,
        "pem fuel cell": 3,
        "direct methanol fuel cell": 3,
        "molten carbonate fuel cell": 3,
        "phosphoric acid fuel cell": 3,
        "alkaline fuel cell": 3,
        "oxygen vacancy conductivity": 3,
        "oxide ion conductor": 3,
        "protonic conductor": 3,
        "electrochemical device": 3,
        "electrochemical energy conversion": 3,
        "electrochemical energy storage": 3,
        "hydrogen oxidation reaction": 3,
        "oxygen reduction reaction": 3,
        "perovskite fuel cell": 3,
        "perovskite electrolysis": 3,
        "ceramic electrolyte": 3,
        "polymer electrolyte": 3,
        "electrolyte membrane": 3,
        "cathode material energy": 3,
        "anode material energy": 3,
        "interconnect material": 2,
        "sealant material": 2,
        "reversible fuel cell": 3,
        "regenerative fuel cell": 3,
        "micro combined heat and power": 2,
        "stationary fuel cell": 2,
        "portable fuel cell": 2,
        "hydrogen purity": 2,
        "hydrogen compression": 2,
        "hydrogen liquefaction": 2,
        "hydrogen storage": 3,
        "metal hydride hydrogen": 3,
        "chemical hydrogen storage": 3,
        "liquid organic hydrogen carrier": 3,
        "ammonia hydrogen carrier": 2,
        "formic acid hydrogen": 2,
        "tidal energy": 3,
        "wave energy": 3,
        "geothermal energy": 3,
        "biomass energy": 3,
        "biogas energy": 3,
        "bioethanol production": 3,
        "biodiesel production": 3,
        "synthetic fuel": 2,
        "e-fuel": 2,
        "power to gas": 2,
        "power to liquid": 2,
        "carbon neutral fuel": 3,
        "zero carbon fuel": 3,
    },
    "single_words": {
        "biofuel": 3,
        "hydropower": 3,
        "decarbonization": 3,
        "photovoltaics": 3,
        "electrification": 3,
        "catalysis": 3,
        "photocatalysis": 3,
        "electrocatalysis": 3,
        "electrolyzer": 3,
        "battery": 3,
        "supercapacitor": 3,
        "thermoelectric": 2,
        "geothermal": 2,
        "biomass": 2,
        "biogas": 2,
        "biomethane": 2,
        "bioethanol": 2,
        "biodiesel": 2,
        "piezoelectric": 2,
        "triboelectric": 2,
        "microgrid": 2,
        "off-grid": 3,
        "perovskite": 2,
        "proton": 3,
        "protonic": 3,
        "electrolyte": 3,
        "conductivity": 2,
        "conduction": 2,
        "oxygen vacancy": 2,
        "hydrogen": 3,
        "electrochemical": 3,
        "electrolysis": 3,
        "faradaic": 2,
        "galvanostatic": 2,
        "potentiostatic": 2,
        "impedance spectroscopy": 2,
        "current density": 2,
        "power density": 2,
        "open circuit voltage": 2,
        "cell voltage": 2,
        "overpotential": 2,
        "polarization curve": 2,
        "tafel slope": 2,
        "exchange current density": 2,
        "activation energy conduction": 2,
        "migration energy": 2,
        "hopping mechanism": 2,
        "grotthuss mechanism": 2,
        "vehicle mechanism": 2,
        "wave": 2,
        "tidal": 2,
        "hydroelectric": 2,
    },
    "stems": {
        "energy": 2,
        "renew": 2,
        "solar": 2,
        "wind": 2,
        "biofuel": 2,
        "hydro": 2,
        "catalys": 2,
        "electrocatalys": 2,
        "photocatalys": 2,
        "hydrogen": 2,
        "electrolysis": 2,
        "photovolta": 2,
        "batter": 2,
        "capacitor": 2,
        "electrif": 2,
        "proton": 2,
        "conduct": 2,
        "electrolyt": 2,
        "electrochem": 2,
        "fuel": 2,
    }
}

# ============================================================================
# SDG 8: Decent Work & Economic Growth (55+ terms)
# ============================================================================

SDG8_KEYWORDS = {
    "exact_phrases": {
        "decent work": 3,
        "labor rights": 3,
        "forced labor": 3,
        "child labor": 3,
        "minimum wage": 3,
        "informal economy": 3,
        "job creation": 3,
        "economic growth": 3,
        "working conditions": 3,
        "occupational safety": 3,
        "fair wages": 3,
        "workers' rights": 3,
        "precarious employment": 3,
        "youth unemployment": 3,
        "labor exploitation": 3,
        "gig economy": 2,
        "decent job": 3,
        "labor market": 2,
        "wage inequality": 2,
        "collective bargaining": 2,
        "workplace safety": 3,
        "GDP per capita": 2,
        "economic productivity": 2,
        "full employment": 3,
        "labor participation": 2,
        "skill development": 2,
        "workforce development": 2,
        "green jobs": 3,
        "sustainable tourism": 2,
        "economic diversification": 2,
        "innovation economy": 2,
        "digital economy": 2,
        "circular economy jobs": 2,
        "social enterprise": 2,
        "labor productivity": 2,
        "economic resilience": 2,
        "living wage": 3,
        "working poor": 2,
        "labor standard": 2,
        "occupational health": 2,
    },
    "single_words": {
        "unemployment": 3,
        "productivity": 2,
        "entrepreneurship": 2,
        "employment": 2,
        "union": 2,
        "underemployment": 2,
        "apprenticeship": 2,
        "internship": 2,
        "cooperative": 2,
        "livelihood": 2,
        "wage": 2,
    },
    "stems": {
        "employ": 2,
        "labor": 2,
        "work": 2,
        "job": 2,
        "wage": 2,
        "econom": 2,
        "growth": 2,
    }
}

# ============================================================================
# SDG 9: Industry, Innovation & Infrastructure (UPDATED: 210+ terms including software tools, scientific communication, AI)
# ============================================================================

SDG9_KEYWORDS = {
    "exact_phrases": {
        # Core industry and innovation
        "technology transfer": 3,
        "sustainable industry": 3,
        "materials science": 3,
        "advanced materials": 3,
        "thin film": 3,
        "quantum dot": 3,
        "2d materials": 3,
        "carbon nanotube": 3,
        "metal organic framework": 3,
        "covalent organic framework": 3,
        "smart material": 3,
        "functional material": 3,
        "additive manufacturing": 2,
        "digital infrastructure": 3,
        "supply chain": 2,
        "research and development": 2,
        "industrial ecology": 2,
        "shape memory alloy": 2,
        "photonic crystal": 2,
        "3d printing": 2,
        "4d printing": 2,
        "industry 4.0": 2,
        "industrial automation": 2,
        "smart manufacturing": 2,
        "digital twin": 2,
        "internet of things industry": 2,
        "artificial intelligence industry": 2,
        "synthetic method": 3,
        "organic synthesis": 3,
        "chemical synthesis": 3,
        "reaction development": 3,
        "methodology development": 3,
        "catalytic method": 3,
        "synthetic approach": 3,
        "synthetic strategy": 3,
        "reaction optimization": 3,
        "reaction condition": 3,
        "reaction scope": 3,
        "substrate scope": 3,
        "functional group tolerance": 3,
        "scalable synthesis": 3,
        "gram-scale synthesis": 3,
        "flow chemistry": 3,
        "continuous flow": 3,
        "microwave-assisted synthesis": 3,
        "sonochemical synthesis": 3,
        "mechanochemical synthesis": 3,
        
        # Materials for non-energy applications
        "structural material": 3,
        "construction material": 3,
        "building material": 3,
        "cement chemistry": 2,
        "concrete technology": 2,
        "ceramic processing": 2,
        "metallurgical process": 2,
        "steel manufacturing": 2,
        "alloy development": 2,
        "composite material": 2,
        "polymer composite": 2,
        "biocomposite": 2,
        "nanocomposite": 2,
        "coating technology": 2,
        "surface engineering": 2,
        "corrosion protection": 2,
        "wear resistance": 2,
        "thermal barrier coating": 2,
        
        # NEW: Software tools and web applications
        "web-based application": 3,
        "software tool": 3,
        "analytical tool": 3,
        "data visualization": 3,
        "heatmap generator": 3,
        "histogram visualizer": 3,
        "distribution visualizer": 3,
        "speed graph generator": 3,
        "data storytelling": 3,
        "graphical representation": 3,
        "visualization toolkit": 3,
        "analytical precision": 3,
        "statistical summary": 3,
        "univariate analysis": 3,
        "bivariate analysis": 3,
        "performance metrics": 3,
        "user-centered design": 2,
        "accessibility tool": 2,
        "matrix data analysis": 3,
        "min max analyzer": 3,
        "data analysis platform": 3,
        "scientific computing": 3,
        "computational tool": 3,
        "data processing software": 2,
        "algorithm development": 3,
        "machine learning tool": 3,
        "artificial intelligence tool": 3,
        "deep learning framework": 3,
        "data mining software": 3,
        "statistical software": 3,
        "visual analytics": 3,
        "interactive visualization": 3,
        "dashboard tool": 2,
        "data exploration": 2,
        "pattern recognition software": 3,
        
        # NEW: AI detection and linguistic analysis
        "ai detection": 3,
        "ai generated text": 3,
        "linguistic pattern analysis": 3,
        "proprietary analytical tool": 3,
        "manuscript assessment": 3,
        "reference analyzer": 3,
        "citation verification": 3,
        "academic database cross-referencing": 3,
        "cta i detector": 3,
        "comprehensive reference list analyzer": 3,
        "text analysis algorithm": 3,
        "language model detection": 3,
        "generative ai detection": 3,
        "llm detection": 3,
        "chatbot detection": 3,
        "synthetic text detection": 3,
        "authorship verification": 3,
        "plagiarism detection": 2,
        "similarity detection": 2,
        "citation analysis": 3,
        "bibliometric tool": 2,
        "reference checking": 2,
        
        # NEW: Scientific communication and visualization
        "scientific visualization": 3,
        "research visualization": 3,
        "data visualization tool": 3,
        "chart generator": 2,
        "plot generator": 2,
        "graph generator": 2,
        "interactive dashboard": 2,
        "data dashboard": 2,
        "analytics platform": 2,
        "business intelligence tool": 2,
        "report generator": 2,
        "automated reporting": 2,
        "data analysis pipeline": 2,
        "workflow automation": 2,
        "computational notebook": 2,
        "reproducible research": 2,
        "open source tool": 2,
        "scientific software": 3,
    },
    "single_words": {
        "infrastructure": 3,
        "industrialization": 3,
        "innovation": 3,
        "nanomaterials": 3,
        "composite": 2,
        "semiconductor": 3,
        "graphene": 3,
        "zeolite": 2,
        "mxene": 3,
        "perovskite": 2,
        "manufacturing": 2,
        "R&D": 2,
        "broadband": 2,
        "connectivity": 2,
        "factory": 2,
        "automation": 2,
        "patent": 2,
        "nanotechnology": 3,
        "biotechnology": 2,
        "biomaterials": 2,
        "hydrogel": 2,
        "polymer": 2,
        "plastic": 2,
        "elastomer": 2,
        "ceramic": 2,
        "metal alloy": 2,
        "metamaterial": 2,
        "plasmonic": 2,
        "nanoparticle": 2,
        "nanowire": 2,
        "nanotube": 2,
        "nanosheet": 2,
        "bioprinting": 2,
        "robotics": 2,
        "synthesis": 3,
        "preparation": 3,
        "methodology": 3,
        "protocol": 2,
        "procedure": 2,
        "reagent": 2,
        "catalyst": 3,
        "selectivity": 2,
        "conversion": 2,
        "optimization": 2,
        "characterization": 2,
        "discovery": 2,
        
        # Generic terms with reduced weight
        "crystal structure": 1,
        "defect structure": 1,
        "solid solution": 1,
        "atomic arrangement": 1,
        "structural disorder": 1,
        "local structure": 1,
        
        # NEW single words for software and tools
        "heatmap": 3,
        "histogram": 3,
        "visualizer": 3,
        "analyzer": 3,
        "dashboard": 2,
        "toolkit": 2,
        "algorithm": 2,
        "software": 3,
        "application": 2,
        "platform": 2,
        "framework": 2,
        "library": 2,
        "api": 2,
        "workflow": 2,
        "pipeline": 2,
        "detector": 3,
        "verifier": 2,
        "validator": 2,
        "cross-referencer": 2,
    },
    "stems": {
        "material": 2,
        "industr": 2,
        "innov": 2,
        "infrastructur": 2,
        "manufactur": 2,
        "nanomateri": 2,
        "nanotech": 2,
        "synthes": 2,
        "fabricat": 2,
        "technolog": 2,
        "prepar": 2,
        "methodolog": 2,
        "catalys": 2,
        "optimiz": 2,
        "character": 2,
        "discoveri": 2,
        "visual": 2,
        "analyt": 2,
        "comput": 2,
        "algorithm": 2,
        "softwar": 2,
        "detect": 2,
    }
}

# ============================================================================
# SDG 10: Reduced Inequalities (50+ terms)
# ============================================================================

SDG10_KEYWORDS = {
    "exact_phrases": {
        "income inequality": 3,
        "wealth gap": 3,
        "social exclusion": 3,
        "Gini coefficient": 3,
        "social mobility": 3,
        "economic disparity": 3,
        "inclusive growth": 3,
        "vulnerable group": 3,
        "ethnic inequality": 3,
        "socioeconomic inequality": 3,
        "wealth concentration": 3,
        "social justice": 2,
        "equal opportunity": 3,
        "horizontal inequality": 3,
        "vertical inequality": 3,
        "relative poverty": 2,
        "affirmative action": 2,
        "redistributive policy": 2,
        "universal access": 2,
        "racial inequality": 3,
        "ethnic minority": 2,
        "religious minority": 2,
        "linguistic minority": 2,
        "disability inclusion": 2,
        "social integration": 2,
        "social cohesion": 2,
        "discriminatory law": 2,
        "inequality reduction": 3,
        "pro-poor growth": 3,
        "inclusive development": 2,
        "leave no one behind": 3,
    },
    "single_words": {
        "marginalization": 3,
        "discrimination": 3,
        "minority": 2,
        "indigenous": 2,
        "refugee": 3,
        "migrant": 2,
        "inequality": 3,
        "redistribution": 2,
        "remittance": 2,
        "diaspora": 2,
        "exclusion": 2,
        "stigmatization": 2,
    },
    "stems": {
        "inequ": 2,
        "dispar": 2,
        "exclus": 2,
        "margin": 2,
        "refuge": 2,
        "discrimin": 2,
    }
}

# ============================================================================
# SDG 11: Sustainable Cities & Communities (60+ terms)
# ============================================================================

SDG11_KEYWORDS = {
    "exact_phrases": {
        "public transport": 3,
        "affordable housing": 3,
        "waste management": 3,
        "air pollution": 3,
        "green space": 2,
        "urban sprawl": 3,
        "disaster resilience": 3,
        "urban poverty": 3,
        "informal settlement": 3,
        "smart city": 2,
        "green building": 2,
        "indoor air quality": 2,
        "volatile organic compound": 2,
        "particulate matter": 2,
        "urban planning": 2,
        "sustainable transport": 3,
        "cycling infrastructure": 2,
        "bus rapid transit": 2,
        "light rail": 2,
        "electric vehicle": 2,
        "urban heat island": 2,
        "green roof": 2,
        "vertical garden": 2,
        "permeable pavement": 2,
        "stormwater management": 2,
        "flood resilience": 2,
        "earthquake resilience": 2,
        "heritage preservation": 2,
        "cultural heritage": 2,
        "urban regeneration": 2,
        "housing crisis": 2,
        "homelessness urban": 2,
        "municipal waste": 2,
        "urban agriculture": 2,
        "community garden": 2,
        "public space": 2,
        "urban governance": 2,
        "noise pollution": 2,
        "light pollution": 2,
        "walkable city": 2,
        "bike sharing": 2,
        "car sharing": 2,
        "zero emission vehicle": 2,
    },
    "single_words": {
        "urban": 3,
        "slum": 3,
        "urbanization": 2,
        "walkability": 2,
        "metro": 2,
        "gentrification": 2,
        "placemaking": 2,
        "megacity": 2,
        "suburb": 2,
        "conurbation": 2,
    },
    "stems": {
        "city": 2,
        "hous": 2,
        "transport": 2,
        "pollut": 2,
        "waste": 2,
        "resili": 2,
        "urban": 2,
    }
}

# ============================================================================
# SDG 12: Responsible Consumption & Production (70+ terms)
# ============================================================================

SDG12_KEYWORDS = {
    "exact_phrases": {
        "circular economy": 3,
        "sustainable consumption": 3,
        "plastic pollution": 3,
        "chemical waste": 3,
        "hazardous waste": 3,
        "waste valorization": 3,
        "plastic recycling": 3,
        "polymer degradation": 3,
        "green chemistry": 3,
        "atom economy": 2,
        "solvent free": 2,
        "renewable feedstock": 3,
        "biomass conversion": 3,
        "lignin valorization": 3,
        "food waste": 3,
        "life cycle assessment": 3,
        "material footprint": 3,
        "zero waste": 3,
        "resource efficiency": 3,
        "closed loop": 3,
        "industrial symbiosis": 2,
        "sustainable packaging": 3,
        "biodegradable plastic": 3,
        "single-use plastic": 3,
        "microplastic pollution": 3,
        "waste-to-energy": 2,
        "pyrolysis waste": 2,
        "gasification waste": 2,
        "landfill reduction": 2,
        "extended producer responsibility": 3,
        "product stewardship": 2,
        "sustainable procurement": 3,
        "green supply chain": 2,
        "carbon labeling": 2,
        "environmental footprint": 2,
        "water footprint": 2,
        "ecological footprint": 2,
        "sustainable lifestyle": 2,
        "conscious consumption": 2,
        "e-waste recycling": 3,
        "battery recycling": 3,
        "composting facility": 2,
        "material recovery": 2,
        "resource recovery": 2,
    },
    "single_words": {
        "waste": 3,
        "recycling": 3,
        "e-waste": 3,
        "overconsumption": 3,
        "biodegradable": 3,
        "bioplastic": 3,
        "cellulose": 2,
        "composting": 2,
        "upcycling": 2,
        "downcycling": 2,
        "compostable": 2,
        "ecodesign": 2,
        "minimalism": 2,
        "remanufacturing": 2,
        "reuse": 2,
        "repair": 2,
    },
    "stems": {
        "recycl": 2,
        "consumpt": 2,
        "degrad": 2,
        "biodegrad": 2,
        "bioplast": 2,
        "valor": 2,
        "circular": 2,
        "feedstock": 2,
        "biomass": 2,
        "packag": 2,
    }
}

# ============================================================================
# SDG 13: Climate Action (60+ terms)
# ============================================================================

SDG13_KEYWORDS = {
    "exact_phrases": {
        "climate change": 3,
        "global warming": 3,
        "greenhouse gas": 3,
        "CO2 emission": 3,
        "carbon emission": 3,
        "net zero": 3,
        "carbon neutrality": 3,
        "climate adaptation": 3,
        "climate mitigation": 3,
        "carbon capture": 3,
        "CO2 capture": 3,
        "carbon utilization": 3,
        "CO2 conversion": 3,
        "direct air capture": 3,
        "sea level rise": 3,
        "extreme weather": 3,
        "Paris Agreement": 3,
        "carbon budget": 3,
        "climate resilience": 3,
        "methane capture": 3,
        "carbon dioxide removal": 3,
        "climate risk": 3,
        "climate disaster": 3,
        "climate policy": 2,
        "climate finance": 2,
        "loss and damage": 3,
        "tipping point": 3,
        "temperature rise": 3,
        "climate vulnerability": 3,
        "climate justice": 2,
        "climate action": 3,
        "emission reduction": 3,
        "methane emission": 3,
        "nitrous oxide": 2,
        "fluorinated gas": 2,
        "carbon sink": 2,
        "blue carbon": 2,
        "nature-based solution": 2,
        "climate engineering": 2,
        "carbon offset": 2,
        "carbon credit": 2,
        "emission trading": 2,
    },
    "single_words": {
        "decarbonization": 3,
        "drought": 2,
        "flood": 2,
        "heatwave": 2,
        "wildfire": 2,
        "hurricane": 2,
        "cyclone": 2,
        "typhoon": 2,
        "monsoon": 2,
        "permafrost": 2,
    },
    "stems": {
        "climat": 2,
        "warm": 2,
        "emiss": 2,
        "carbon": 2,
        "captur": 2,
        "mitig": 2,
        "adapt": 2,
        "neutral": 2,
        "greenhous": 2,
    }
}

# ============================================================================
# SDG 14: Life Below Water (60+ terms)
# ============================================================================

SDG14_KEYWORDS = {
    "exact_phrases": {
        "coral reef": 3,
        "marine pollution": 3,
        "plastic in ocean": 3,
        "marine protected area": 3,
        "ocean acidification": 3,
        "marine debris": 3,
        "marine ecosystem": 3,
        "marine biodiversity": 3,
        "ocean warming": 3,
        "marine toxicology": 2,
        "blue economy": 2,
        "coastal zone": 2,
        "kelp forest": 2,
        "ocean conservation": 3,
        "sustainable fishing": 3,
        "illegal fishing": 3,
        "marine reserve": 3,
        "ocean governance": 2,
        "deep sea mining": 2,
        "coral bleaching": 3,
        "marine heatwave": 2,
        "sea turtle": 2,
        "marine mammal": 2,
        "shark conservation": 2,
        "fish stock": 2,
        "fishing quota": 2,
        "marine spatial planning": 2,
        "ocean observing": 2,
        "marine chemistry": 2,
        "ocean biogeochemistry": 2,
        "tidal flat": 2,
        "sea grass": 2,
        "mangrove forest": 2,
        "estuarine ecosystem": 2,
        "coastal wetland": 2,
    },
    "single_words": {
        "marine": 3,
        "ocean": 3,
        "overfishing": 3,
        "microplastic": 3,
        "nanoplastic": 3,
        "bycatch": 3,
        "aquaculture": 2,
        "seafood": 2,
        "fishery": 2,
        "mangrove": 2,
        "seagrass": 2,
        "whale": 2,
        "dolphin": 2,
        "estuary": 2,
        "lagoon": 2,
        "cetacean": 2,
        "pinniped": 2,
    },
    "stems": {
        "ocean": 2,
        "marin": 2,
        "fish": 2,
        "plastic": 2,
        "microplast": 2,
        "acidif": 2,
        "ecosystem": 2,
        "biodivers": 2,
        "coral": 2,
    }
}

# ============================================================================
# SDG 15: Life On Land (65+ terms)
# ============================================================================

SDG15_KEYWORDS = {
    "exact_phrases": {
        "land degradation": 3,
        "habitat loss": 3,
        "soil remediation": 2,
        "heavy metal soil": 2,
        "endangered species": 3,
        "invasive species": 3,
        "biodiversity loss": 3,
        "ecosystem service": 2,
        "soil erosion": 3,
        "land use change": 2,
        "forest fragmentation": 3,
        "species extinction": 3,
        "restoration ecology": 2,
        "protected area": 2,
        "national park": 2,
        "wildlife corridor": 2,
        "ecological connectivity": 2,
        "soil contamination": 2,
        "land rehabilitation": 2,
        "mine tailings": 2,
        "ecological restoration": 2,
        "native species": 2,
        "keystone species": 2,
        "flagship species": 2,
        "umbrella species": 2,
        "indicator species": 2,
        "pollinator decline": 2,
        "insect decline": 2,
        "amphibian decline": 2,
        "bird conservation": 2,
    },
    "single_words": {
        "deforestation": 3,
        "biodiversity": 3,
        "ecosystem": 3,
        "desertification": 3,
        "phytoremediation": 2,
        "bioremediation": 2,
        "reforestation": 3,
        "wildlife": 3,
        "poaching": 3,
        "terrestrial": 3,
        "mangrove": 2,
        "wetland": 2,
        "conservation": 2,
        "forest": 2,
        "rewilding": 2,
        "agroforestry": 2,
        "brownfield": 2,
        "pollinator": 2,
        "fauna": 2,
        "flora": 2,
        "biota": 2,
    },
    "stems": {
        "deforest": 2,
        "ecosystem": 2,
        "habitat": 2,
        "species": 2,
        "remediat": 2,
        "reforest": 2,
        "conserv": 2,
        "terrestri": 2,
        "biodivers": 2,
    }
}

# ============================================================================
# SDG 16: Peace, Justice & Strong Institutions (UPDATED: 95+ terms including editorial processes, publication ethics)
# ============================================================================

SDG16_KEYWORDS = {
    "exact_phrases": {
        # Core peace and justice
        "rule of law": 3,
        "access to justice": 3,
        "human rights": 3,
        "armed conflict": 3,
        "organized crime": 3,
        "human trafficking": 3,
        "civil war": 3,
        "legal aid": 3,
        "crime prevention": 2,
        "judicial independence": 2,
        "transitional justice": 3,
        "international law": 2,
        "humanitarian law": 2,
        "refugee protection": 2,
        "internally displaced": 2,
        "birth registration": 2,
        "legal identity": 2,
        "access to information": 2,
        "press freedom": 2,
        "civil society": 2,
        "good governance": 2,
        "institutional reform": 2,
        "police reform": 2,
        "prison reform": 2,
        "restorative justice": 2,
        
        # NEW: Editorial processes and publication ethics
        "editorial process": 3,
        "editorial decision": 3,
        "manuscript review": 3,
        "peer review": 3,
        "publication ethics": 3,
        "ethical publishing": 3,
        "research integrity": 3,
        "transparent publishing": 3,
        "editorial board": 3,
        "journal commitment": 3,
        "evidence-informed decision": 3,
        "academic publishing practice": 3,
        "scholarly communication ethics": 3,
        "open science practice": 3,
        "responsible research workflow": 3,
        "manuscript assessment": 3,
        "editorial policy": 3,
        "conflict of interest": 3,
        "authorship dispute": 3,
        "retraction policy": 3,
        "correction policy": 3,
        "peer review integrity": 3,
        "double blind review": 2,
        "single blind review": 2,
        "open peer review": 2,
        "post publication review": 2,
        "predatory publishing": 3,
        "paper mill detection": 3,
        "research misconduct": 3,
        "data fabrication": 3,
        "image manipulation": 3,
        "plagiarism policy": 2,
        "citation manipulation": 3,
        "self plagiarism": 2,
        "duplicate publication": 3,
        "salami slicing": 2,
        "ghost authorship": 3,
        "guest authorship": 3,
        "corresponding author responsibility": 2,
        "editorial independence": 3,
        "journal transparency": 3,
        "open access policy": 2,
        "publication malpractice": 3,
        
        # NEW: Research governance
        "research governance": 3,
        "institutional review board": 3,
        "research ethics committee": 3,
        "ethical approval": 2,
        "informed consent": 2,
        "data protection compliance": 2,
        "responsible conduct of research": 3,
        "research reproducibility": 2,
        "open data policy": 2,
        "code of conduct": 2,
        "whistleblower protection": 2,
    },
    "single_words": {
        "peace": 3,
        "conflict": 3,
        "violence": 3,
        "corruption": 3,
        "war": 3,
        "anti-corruption": 3,
        "peacebuilding": 3,
        "trafficking": 3,
        "bribery": 3,
        "transparency": 2,
        "accountability": 2,
        "genocide": 3,
        "torture": 3,
        "disarmament": 2,
        "demobilization": 2,
        "reintegration": 2,
        "ceasefire": 2,
        "mediation": 2,
        "diplomacy": 2,
        "statelessness": 2,
        
        # NEW single words for editorial
        "editorial": 3,
        "manuscript": 3,
        "peer-review": 3,
        "ethics": 3,
        "integrity": 3,
        "retraction": 2,
        "correction": 2,
        "misconduct": 3,
        "fabrication": 3,
        "falsification": 3,
    },
    "stems": {
        "peace": 2,
        "conflict": 2,
        "violen": 2,
        "corrupt": 2,
        "justic": 2,
        "rights": 2,
        "traffick": 2,
        "legal": 2,
        "editor": 2,
        "ethic": 2,
        "integr": 2,
        "review": 2,
    }
}

# ============================================================================
# SDG 17: Partnerships for the Goals (45+ terms)
# ============================================================================

SDG17_KEYWORDS = {
    "exact_phrases": {
        "international cooperation": 3,
        "development aid": 3,
        "technology transfer": 3,
        "capacity building": 3,
        "global partnership": 3,
        "south-south cooperation": 3,
        "official development assistance": 3,
        "global governance": 2,
        "finance for development": 3,
        "public-private": 3,
        "knowledge sharing": 2,
        "resource mobilization": 3,
        "policy coherence": 2,
        "global solidarity": 3,
        "triangular cooperation": 3,
        "global fund": 2,
        "stakeholder engagement": 2,
        "data revolution": 2,
        "capacity development": 2,
        "technical assistance": 2,
        "aid effectiveness": 2,
        "development cooperation": 2,
        "donor coordination": 2,
        "impact investing": 2,
        "blended finance": 2,
        "green bond": 2,
        "social bond": 2,
        "sustainable finance": 2,
        "tax cooperation": 2,
        "illicit financial flows": 2,
        "debt sustainability": 2,
        "trade facilitation": 2,
        "fair trade": 2,
        "ethical supply chain": 2,
        "global indicator framework": 2,
        "monitoring and evaluation": 2,
        "SDG reporting": 2,
        "corporate sustainability": 2,
        "multi-stakeholder partnership": 3,
        "public-private partnership": 3,
    },
    "single_words": {
        "partnership": 3,
        "multi-stakeholder": 3,
        "collaboration": 2,
        "multilateral": 2,
        "philanthropy": 2,
        "ESG": 2,
    },
    "stems": {
        "partnership": 2,
        "cooper": 2,
        "collabor": 2,
        "global": 2,
    }
}

# ============================================================================
# MASTER DICTIONARY (for import in app.py)
# ============================================================================

SDG_KEYWORDS = {
    1: SDG1_KEYWORDS,
    2: SDG2_KEYWORDS,
    3: SDG3_KEYWORDS,
    4: SDG4_KEYWORDS,
    5: SDG5_KEYWORDS,
    6: SDG6_KEYWORDS,
    7: SDG7_KEYWORDS,
    8: SDG8_KEYWORDS,
    9: SDG9_KEYWORDS,
    10: SDG10_KEYWORDS,
    11: SDG11_KEYWORDS,
    12: SDG12_KEYWORDS,
    13: SDG13_KEYWORDS,
    14: SDG14_KEYWORDS,
    15: SDG15_KEYWORDS,
    16: SDG16_KEYWORDS,
    17: SDG17_KEYWORDS,
}

# SDG Names for reference
SDG_NAMES = {
    1: "No Poverty",
    2: "Zero Hunger",
    3: "Good Health & Well-being",
    4: "Quality Education",
    5: "Gender Equality",
    6: "Clean Water & Sanitation",
    7: "Affordable & Clean Energy",
    8: "Decent Work & Economic Growth",
    9: "Industry, Innovation & Infrastructure",
    10: "Reduced Inequalities",
    11: "Sustainable Cities & Communities",
    12: "Responsible Consumption & Production",
    13: "Climate Action",
    14: "Life Below Water",
    15: "Life On Land",
    16: "Peace, Justice & Strong Institutions",
    17: "Partnerships for the Goals"
}

# SDG Colors for visualization
SDG_COLORS = {
    1: "#E5243B",
    2: "#DDA63A",
    3: "#4C9F38",
    4: "#C5192D",
    5: "#FF3A21",
    6: "#26BDE2",
    7: "#FCC30B",
    8: "#A21942",
    9: "#FD6925",
    10: "#DD1367",
    11: "#FD9D24",
    12: "#BF8B2E",
    13: "#3F7E44",
    14: "#0A97D9",
    15: "#56C02B",
    16: "#00689D",
    17: "#19486A"
}

# SDG Icons emoji fallback
SDG_ICONS = {
    1: "🚫",
    2: "🍞",
    3: "❤️",
    4: "📚",
    5: "⚧",
    6: "💧",
    7: "⚡",
    8: "💼",
    9: "🏭",
    10: "⚖️",
    11: "🏙️",
    12: "♻️",
    13: "🌍",
    14: "🌊",
    15: "🌳",
    16: "🕊️",
    17: "🤝"
}
